#!/usr/bin/env node
/**
 * dotmask proxy server — MITM HTTPS proxy entry point.
 * Intercepts requests to AI API domains and masks secrets in the request body.
 *
 * Started by launchd via daemon.ts. Can also be run manually:
 *   node dist/proxy/server.js --port 18787
 */

import http from "node:http";
import net from "node:net";
import tls from "node:tls";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { spawnSync } from "node:child_process";
import { CA_DIR, CA_CERT_PATH, CA_KEY_PATH, DOTMASK_DIR } from "./cert.js";
import { loadAllowedHosts, normalizeHost } from "./config.js";
import { parseCompleteHttpRequest, sanitizeRequestBody } from "./http.js";
import { parsePortFlag } from "../utils.js";

// ── Config ───────────────────────────────────────────────────────────────


const args = process.argv.slice(2);
const PORT = parsePortFlag(args, 18787);

const DEBUG = process.env.DOTMASK_DEBUG === "1";
function dbg(...msg: unknown[]): void {
  if (DEBUG) console.error("[dotmask][proxy]", ...msg);
}

const ALLOWED_HOSTS = loadAllowedHosts();

function shouldMitmHost(hostname: string): boolean {
  return ALLOWED_HOSTS.has(normalizeHost(hostname));
}

// ── TLS: per-hostname certificate generation ──────────────────────────────────

// http-mitm-proxy generates certs in its own dir; we do it manually here
// to stay dependency-light and understand the full flow.
// We use node's built-in tls + the CA files generated by http-mitm-proxy on first start.

interface CertCache {
  cert: Buffer;
  key: Buffer;
}
const certCache = new Map<string, CertCache>();

/**
 * Generate a host certificate signed by our CA.
 * We shell out to `openssl` (always available on macOS) to keep code simple.
 */
function getCertForHost(hostname: string): CertCache {
  if (certCache.has(hostname)) return certCache.get(hostname)!;

  const caCert = fs.readFileSync(CA_CERT_PATH);
  const caKey = fs.readFileSync(CA_KEY_PATH);

  // Use node:crypto to generate key pair
  const { privateKey, publicKey } = crypto.generateKeyPairSync("rsa", { modulusLength: 2048 });

  // We need to create a cert; use openssl CLI (always on macOS)
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "dotmask-cert-"));
  const keyPath = path.join(tmpDir, "host.key");
  const csrPath = path.join(tmpDir, "host.csr");
  const certPath = path.join(tmpDir, "host.crt");
  const extPath = path.join(tmpDir, "ext.cnf");
  const caKeyPath_ = path.join(tmpDir, "ca.key");
  const caCertPath_ = path.join(tmpDir, "ca.crt");

  try {
    fs.writeFileSync(keyPath, privateKey.export({ type: "pkcs8", format: "pem" }));
    fs.writeFileSync(caKeyPath_, caKey);
    fs.writeFileSync(caCertPath_, caCert);

    const ext = `[req]\nreq_extensions = v3_req\ndistinguished_name = req_distinguished_name\n[req_distinguished_name]\n[v3_req]\nsubjectAltName = DNS:${hostname}\nbasicConstraints = CA:FALSE\n`;
    fs.writeFileSync(extPath, ext);

    // Generate CSR
    execOpenssl(["req", "-new", "-key", keyPath, "-subj", `/CN=${hostname}`, "-out", csrPath]);
    // Sign with CA
    execOpenssl([
      "x509", "-req", "-in", csrPath, "-CA", caCertPath_, "-CAkey", caKeyPath_,
      "-CAcreateserial", "-out", certPath, "-days", "825",
      "-extfile", extPath, "-extensions", "v3_req",
    ]);

    const cert = fs.readFileSync(certPath);
    const key = fs.readFileSync(keyPath);
    const result = { cert, key };
    certCache.set(hostname, result);
    return result;
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

function execOpenssl(args: string[]): void {
  const res = spawnSync("openssl", args, { stdio: "pipe" });
  if (res.status !== 0) throw new Error(`openssl failed: ${res.stderr?.toString()}`);
}

// ── CA generation (first run) ─────────────────────────────────────────────────

function ensureCA(): void {
  if (fs.existsSync(CA_CERT_PATH) && fs.existsSync(CA_KEY_PATH)) return;

  fs.mkdirSync(CA_DIR, { recursive: true });
  fs.chmodSync(CA_DIR, 0o700);

  // Generate CA key
  execOpenssl(["genrsa", "-out", CA_KEY_PATH, "4096"]);
  // Generate CA cert
  execOpenssl([
    "req", "-new", "-x509", "-days", "3650", "-key", CA_KEY_PATH,
    "-out", CA_CERT_PATH,
    "-subj", "/CN=dotmask-proxy-ca/O=dotmask/OU=dotmask-proxy-ca",
    "-addext", "basicConstraints=critical,CA:TRUE",
    "-addext", "keyUsage=critical,keyCertSign,cRLSign",
  ]);

  fs.chmodSync(CA_KEY_PATH, 0o600);
  fs.chmodSync(CA_CERT_PATH, 0o644);
  console.log(`[dotmask] CA cert generated at ${CA_CERT_PATH}`);
}

// ── Request body masking ──────────────────────────────────────────────────────

function writeProxyErrorResponse(clientTls: tls.TLSSocket, message: string): void {
  if (clientTls.destroyed) return;
  const body = JSON.stringify({ error: message });
  clientTls.end(
    `HTTP/1.1 502 Bad Gateway\r\n` +
    `Content-Type: application/json\r\n` +
    `Content-Length: ${Buffer.byteLength(body, "utf8")}\r\n` +
    `Connection: close\r\n\r\n` +
    body,
    "utf8",
  );
}

// ── HTTPS CONNECT tunnel handler ──────────────────────────────────────────────

function handleConnect(
  req: http.IncomingMessage,
  clientSocket: net.Socket,
  head: Buffer,
): void {
  const [hostname, portStr] = (req.url ?? "").split(":");
  const targetPort = Number.parseInt(portStr ?? "443", 10) || 443;

  if (!hostname) {
    clientSocket.end("HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n");
    return;
  }

  if (!shouldMitmHost(hostname)) {
    dbg(`CONNECT passthrough: ${hostname}:${targetPort}`);
    const upstreamSocket = net.connect({ host: hostname, port: targetPort });
    let connected = false;

    upstreamSocket.on("connect", () => {
      connected = true;
      clientSocket.write("HTTP/1.1 200 Connection Established\r\n\r\n");
      if (head.length > 0) upstreamSocket.write(head);
      upstreamSocket.pipe(clientSocket);
      clientSocket.pipe(upstreamSocket);
    });

    upstreamSocket.on("error", (e) => {
      dbg("passthrough upstream error:", e.message);
      if (!connected && !clientSocket.destroyed) {
        clientSocket.end("HTTP/1.1 502 Bad Gateway\r\nConnection: close\r\n\r\n");
      }
      upstreamSocket.destroy();
      clientSocket.destroy();
    });

    clientSocket.on("error", () => upstreamSocket.destroy());
    clientSocket.on("close", () => upstreamSocket.destroy());
    upstreamSocket.on("close", () => clientSocket.destroy());
    return;
  }

  dbg(`CONNECT MITM: ${hostname}:${targetPort}`);

  // MITM: respond with 200, then wrap in TLS using our generated cert
  clientSocket.write("HTTP/1.1 200 Connection Established\r\n\r\n");

  let hostCert: CertCache;
  try {
    hostCert = getCertForHost(hostname);
  } catch (e) {
    dbg("cert generation failed:", e);
    clientSocket.destroy();
    return;
  }

  const tlsServer = new tls.TLSSocket(clientSocket, {
    isServer: true,
    cert: hostCert.cert,
    key: hostCert.key,
  });

  if (head.length > 0) {
    clientSocket.unshift(head);
  }

  tlsServer.on("error", (e) => dbg("tls error:", e.message));

  // Parse the decrypted HTTP request
  let pending = Buffer.alloc(0);
  let requestChain = Promise.resolve();
  let connectionFailed = false;

  function startForward(requestLine: string, reqHeaders: Record<string, string>, bodyBuf: Buffer): void {
    requestChain = requestChain.then(async () => {
      if (connectionFailed || tlsServer.destroyed) return;
      await forwardRequest(hostname, targetPort, requestLine, reqHeaders, bodyBuf, tlsServer);
    }).catch((e) => {
      connectionFailed = true;
      dbg("forward request failed:", e);
      writeProxyErrorResponse(
        tlsServer,
        e instanceof Error ? `dotmask blocked request before it left your machine: ${e.message}` : "dotmask blocked request before it left your machine",
      );
      throw e;
    });
  }

  tlsServer.on("data", (chunk: Buffer) => {
    pending = Buffer.concat([pending, chunk]);

    try {
      while (true) {
        const parsed = parseCompleteHttpRequest(pending);
        if (!parsed) return;

        pending = pending.subarray(parsed.bytesConsumed);
        startForward(parsed.requestLine, parsed.headers, parsed.body);
      }
    } catch (err) {
      connectionFailed = true;
      pending = Buffer.alloc(0);
      writeProxyErrorResponse(
        tlsServer,
        err instanceof Error ? `dotmask blocked malformed request: ${err.message}` : "dotmask blocked malformed request",
      );
    }
  });
}

async function forwardRequest(
  hostname: string,
  port: number,
  requestLine: string,
  reqHeaders: Record<string, string>,
  bodyBuf: Buffer,
  clientTls: tls.TLSSocket,
): Promise<void> {
  const method = requestLine.split(" ")[0];
  const urlPath = requestLine.split(" ")[1] ?? "/";

  const contentType = reqHeaders["content-type"] ?? "";
  const contentEncoding = reqHeaders["content-encoding"] ?? "";
  const sanitized = sanitizeRequestBody(bodyBuf, contentType, contentEncoding);
  if (sanitized.count > 0) dbg(`masked ${sanitized.count} secret(s) in request to ${hostname}`);
  const finalBody = sanitized.body;

  const outHeaders: Record<string, string> = { ...reqHeaders };
  outHeaders["content-length"] = String(finalBody.length);
  delete outHeaders["transfer-encoding"];
  outHeaders["accept-encoding"] = "identity";

  await new Promise<void>((resolve, reject) => {
    const outSocket = tls.connect({ host: hostname, port, servername: hostname });
    let settled = false;

    function finish(err?: Error): void {
      if (settled) return;
      settled = true;
      outSocket.destroy();
      if (err) {
        reject(err);
      } else {
        resolve();
      }
    }

    function sendToClient(chunk: Buffer): void {
      if (!clientTls.destroyed) clientTls.write(chunk);
    }

    outSocket.on("error", (e) => {
      dbg("upstream error:", e.message);
      finish(e instanceof Error ? e : new Error(String(e)));
    });
    clientTls.on("error", () => outSocket.destroy());

    outSocket.on("connect", () => {
      const headerLines = Object.entries(outHeaders)
        .map(([k, v]) => `${k}: ${v}`)
        .join("\r\n");
      outSocket.write(`${method} ${urlPath} HTTP/1.1\r\n${headerLines}\r\n\r\n`);
      if (finalBody.length > 0) outSocket.write(finalBody);
    });

    // Provider responses are untrusted input. Forward them byte-for-byte and
    // never materialize a real secret in model-controlled text or tool calls.
    outSocket.on("data", sendToClient);
    outSocket.on("end", () => finish());
  });
}

// ── Main server ───────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  ensureCA();
  dbg("MITM allowlist:", Array.from(ALLOWED_HOSTS));

  const server = http.createServer((req, res) => {
    // Handle plain HTTP (shouldn't happen for AI APIs, but handle gracefully)
    res.writeHead(400);
    res.end("dotmask proxy: use HTTPS\n");
  });

  server.on("connect", handleConnect);

  server.listen(PORT, "127.0.0.1", () => {
    console.log(`[dotmask] proxy listening on localhost:${PORT}`);
  });

  server.on("error", (e) => {
    console.error("[dotmask] proxy server error:", e.message);
    process.exit(1);
  });

  process.on("SIGTERM", () => { server.close(); process.exit(0); });
  process.on("SIGINT", () => { server.close(); process.exit(0); });
}

void main();
